# Generated by Django 3.0.4 on 2020-04-15 04:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lesson3App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
